//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelMaster_MainWindow
    {
        public int ExcelMaster_MainWindow_id { get; set; }
        public Nullable<int> ExcelMaster_Branch_id { get; set; }
        public Nullable<int> ExcelMaster_Educational_Аctivities_id { get; set; }
        public Nullable<int> ExcelMaster_Educational_Monitoring_id { get; set; }
        public Nullable<int> ExcelMaster_State_Сontrol_id { get; set; }
    }
}
