//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelMaster_State_Сontrol
    {
        public int ExcelMaster_State_Сontrol_id { get; set; }
        public string ExcelMaster_State_Сontrol_Name { get; set; }
        public Nullable<int> ExcelMaster_State_Сontrol_AP1 { get; set; }
        public Nullable<int> ExcelMaster_State_Сontrol_AP2 { get; set; }
        public Nullable<int> ExcelMaster_State_Сontrol_AP3 { get; set; }
        public Nullable<int> ExcelMaster_State_Сontrol_AP4 { get; set; }
        public Nullable<int> ExcelMaster_State_Сontrol_Total { get; set; }
    }
}
