//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelMaster_Branch
    {
        public int ExcelMaster_Branch_id { get; set; }
        public string ExcelMaster_Branch_Name { get; set; }
    }
}
