//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelMaster_Educational_Monitoring
    {
        public int ExcelMaster_Educational_Monitoring_id { get; set; }
        public string ExcelMaster_Educational_Monitoring_Name { get; set; }
        public Nullable<int> ExcelMaster_Educational_Monitoring_AP1 { get; set; }
        public Nullable<int> ExcelMaster_Educational_Monitoring_AP2 { get; set; }
        public Nullable<int> ExcelMaster_Educational_Monitoring_AP3 { get; set; }
        public Nullable<int> ExcelMaster_Educational_Monitoring_AP4 { get; set; }
        public Nullable<int> ExcelMaster_Educational_Monitoring_Total { get; set; }
    }
}
